### ISSUE TITLE
Branch branch = gitLabApi.getRepositoryApi().createBranch(122, "feature/wwwwwww_ww", "master");

### ISSUE THREAD

**Issue by dowsam** [gmessner/gitlab-api#12]
com.messners.gitlab.api.GitLabApiException: Branch name invalid
    at com.messners.gitlab.api.AbstractApi.validate(AbstractApi.java:232)
    at com.messners.gitlab.api.AbstractApi.post(AbstractApi.java:79)
    at com.messners.gitlab.api.RepositoryApi.createBranch(RepositoryApi.java:79)
    at com.messners.gitlab.api.TestGitLabApi.testCreateBranche(TestGitLabApi.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by gmessner** [comment]
Can you provide the unit test source code for testCreateBranche() ?

**Comment by dowsam** [comment]
@Test
	public void testCreateBranche() {
		try {
			Branch branch = gitLabApi.getRepositoryApi().createBranch(122,
					"feature/wwwwwww_ww", "master");
			System.out.println(branch);
		} catch (GitLabApiException e) {
			e.printStackTrace();
		}
	}

**Comment by gmessner** [comment]
The createBranch() method has been fixed in the latest release.
